name: Build and deploy Python app to Azure Web Apps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.12'
    
    - name: Install deps into app folder
      run: |
        python -m pip install --upgrade pip --root-user-action=ignore
        pip install -r requirements.txt --target ./.python_packages/lib/site-packages --root-user-action=ignore
      
    - name: Zip artifact
      run: zip -r app.zip . -x "**/.git*"
      
    - uses: azure/webapps-deploy@v3
      with:
        app-name: 'reddit-monitoring-app'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: app.zip
